create table if not exists public.truck_etc_leads (
  id bigint generated by default as identity primary key,
  lead_no text not null unique,
  industry text not null,
  vehicle_count text not null,
  contact_name text not null,
  phone text not null,
  source text not null default '企微货车ETC H5',
  status text not null default '待联系',
  created_at timestamptz not null default timezone('utc', now()),
  constraint truck_etc_leads_status_check check (status in ('待联系', '已联系', '意向明确', '已签约', '暂不办理'))
);

create index if not exists truck_etc_leads_created_at_idx on public.truck_etc_leads (created_at desc);
create index if not exists truck_etc_leads_status_idx on public.truck_etc_leads (status);
create index if not exists truck_etc_leads_industry_idx on public.truck_etc_leads (industry);

alter table public.truck_etc_leads enable row level security;
revoke all on table public.truck_etc_leads from anon, authenticated;

comment on table public.truck_etc_leads is '货车ETC H5客户需求线索台账；仅由服务端使用 service role 访问。';
